apiVersion: v1
kind: Service
metadata:
  name: pet-customer-service
spec:
  type: NodePort
  selector:
    app: pet-customer
  ports:
  - protocol: TCP
    port: 8000       # Service port for internal communication
    targetPort: 8000 # Container's port
  type: ClusterIP   